module Intl.Terms.Sessions
  (Sessions(..)) where

data Sessions
  = Login
  | Register
  | Username
  | Password
  | ConfirmPassword
  | KeyRing
  | KeyRingInstructions
  | RegisterButtonText
  | Logout
  | LoginInstead
  | RegisterInstead
  | CopyKey
  | DownloadKey
  | KeySubtitle
  | Submit
